# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sumofrowbycol <- function(x, beta) {
    .Call('_rgllvm_sumofrowbycol', PACKAGE = 'rgllvm', x, beta)
}

scoref1c <- function(y, x, z, mu, sigma, t, beta, kbeta) {
    .Call('_rgllvm_scoref1c', PACKAGE = 'rgllvm', y, x, z, mu, sigma, t, beta, kbeta)
}

scoref2c <- function(y, x, z, mu, sigma, t, beta, kbeta) {
    .Call('_rgllvm_scoref2c', PACKAGE = 'rgllvm', y, x, z, mu, sigma, t, beta, kbeta)
}

scoreffinalc <- function(y, x, z, mu, sigma, t, w, beta, kbeta) {
    .Call('_rgllvm_scoreffinalc', PACKAGE = 'rgllvm', y, x, z, mu, sigma, t, w, beta, kbeta)
}

getwic <- function(y, z) {
    .Call('_rgllvm_getwic', PACKAGE = 'rgllvm', y, z)
}

getzilrc <- function(z) {
    .Call('_rgllvm_getzilrc', PACKAGE = 'rgllvm', z)
}

xbetamatrixc <- function(x, beta) {
    .Call('_rgllvm_xbetamatrixc', PACKAGE = 'rgllvm', x, beta)
}

exppartin5c <- function(x, z, u, beta) {
    .Call('_rgllvm_exppartin5c', PACKAGE = 'rgllvm', x, z, u, beta)
}

yin5c <- function(y, z, u) {
    .Call('_rgllvm_yin5c', PACKAGE = 'rgllvm', y, z, u)
}

formula5denoc <- function(x, z, u, beta) {
    .Call('_rgllvm_formula5denoc', PACKAGE = 'rgllvm', x, z, u, beta)
}

formula5numerc <- function(y, x, z, u, mu, sigma, t, w, beta, kbeta) {
    .Call('_rgllvm_formula5numerc', PACKAGE = 'rgllvm', y, x, z, u, mu, sigma, t, w, beta, kbeta)
}

formula5forallkc <- function(y, x, z, u, mu, sigma, t, w, beta) {
    .Call('_rgllvm_formula5forallkc', PACKAGE = 'rgllvm', y, x, z, u, mu, sigma, t, w, beta)
}

efficientscorefc <- function(y, x, z, u, mu, sigma, t, w, beta) {
    .Call('_rgllvm_efficientscorefc', PACKAGE = 'rgllvm', y, x, z, u, mu, sigma, t, w, beta)
}

esteqc <- function(y, x, z, u, mu, sigma, t, w, beta) {
    .Call('_rgllvm_esteqc', PACKAGE = 'rgllvm', y, x, z, u, mu, sigma, t, w, beta)
}

esteqfc <- function(y, x, z, u, mu, sigma, t, w, beta) {
    .Call('_rgllvm_esteqfc', PACKAGE = 'rgllvm', y, x, z, u, mu, sigma, t, w, beta)
}

PCLijklc <- function(xij, xkl, beta, sigmaq, t) {
    .Call('_rgllvm_PCLijklc', PACKAGE = 'rgllvm', xij, xkl, beta, sigmaq, t)
}

PCLijklalltc <- function(xij, xkl, beta, sigmaq, t, w) {
    .Call('_rgllvm_PCLijklalltc', PACKAGE = 'rgllvm', xij, xkl, beta, sigmaq, t, w)
}

PCLallc <- function(y, x, beta, sigmaq, t, w) {
    .Call('_rgllvm_PCLallc', PACKAGE = 'rgllvm', y, x, beta, sigmaq, t, w)
}

PCLaikc <- function(i, k, y, x, beta, sigmaq, t, w) {
    .Call('_rgllvm_PCLaikc', PACKAGE = 'rgllvm', i, k, y, x, beta, sigmaq, t, w)
}

firderPCLaikc <- function(i, k, y, x, beta, sigmaq, t, w) {
    .Call('_rgllvm_firderPCLaikc', PACKAGE = 'rgllvm', i, k, y, x, beta, sigmaq, t, w)
}

secderPCLaikc <- function(i, k, y, x, beta, sigmaq, t, w) {
    .Call('_rgllvm_secderPCLaikc', PACKAGE = 'rgllvm', i, k, y, x, beta, sigmaq, t, w)
}

secderPCLaikallc <- function(y, x, beta, sigmaq, t, w) {
    .Call('_rgllvm_secderPCLaikallc', PACKAGE = 'rgllvm', y, x, beta, sigmaq, t, w)
}

varofsthetac <- function(y, x, beta, sigmaq, t, w) {
    .Call('_rgllvm_varofsthetac', PACKAGE = 'rgllvm', y, x, beta, sigmaq, t, w)
}

PCLsandwich <- function(y, x, beta, sigmaq, t, w) {
    .Call('_rgllvm_PCLsandwich', PACKAGE = 'rgllvm', y, x, beta, sigmaq, t, w)
}

test1 <- function(beta) {
    .Call('_rgllvm_test1', PACKAGE = 'rgllvm', beta)
}

firdertest1 <- function(beta) {
    .Call('_rgllvm_firdertest1', PACKAGE = 'rgllvm', beta)
}

secdertest1 <- function(beta) {
    .Call('_rgllvm_secdertest1', PACKAGE = 'rgllvm', beta)
}

pic <- function(xi, beta) {
    .Call('_rgllvm_pic', PACKAGE = 'rgllvm', xi, beta)
}

esteqbetaic <- function(l, y, x, beta) {
    .Call('_rgllvm_esteqbetaic', PACKAGE = 'rgllvm', l, y, x, beta)
}

esteqallbetaic <- function(y, x, beta) {
    .Call('_rgllvm_esteqallbetaic', PACKAGE = 'rgllvm', y, x, beta)
}

sinforcell <- function(k, kprime, x, beta, pimat1) {
    .Call('_rgllvm_sinforcell', PACKAGE = 'rgllvm', k, kprime, x, beta, pimat1)
}

sfisherinforinv <- function(x, beta) {
    .Call('_rgllvm_sfisherinforinv', PACKAGE = 'rgllvm', x, beta)
}

fastLRp_ <- function(x, y, start, eps_f, eps_g, maxit) {
    .Call('_rgllvm_fastLRp_', PACKAGE = 'rgllvm', x, y, start, eps_f, eps_g, maxit)
}

